### ISSUE TITLE
Custom Keyboardのみフォームが隠れちゃう

### ISSUE THREAD

**Issue by matsumo-and** [TakeKiyo/Flutter-CodeScrolling#101]
再発している
ちゃんとPaddingが押し上げる時と押し上げない時がある

**Comment by TakeKiyo** [comment]
まじか

**Comment by TakeKiyo** [comment]
順当に考えると
https://github.com/TakeKiyo/Flutter-CodeScrolling/pull/93/commits/381e3fdd6e2821dcf97baa0c229e83e5e9a80e29
このあたりが怪しそうやな
このissueは任せます

**Comment by TakeKiyo** [comment]
たぶんcloseKeyboardの書き忘れとかの気がする、おれがいったんやってみます

**Comment by TakeKiyo** [comment]
やってみたけどちょっと思ったところではなかったからやっぱり松本くんに任せたい

**Comment by matsumo-and** [comment]
歌詞用とコード用のText交互にタップするとかなり見た感じ良くないということもあって、
かつOn TapじゃなくてFocusNodeで記述すればなんとかなるかもしれないので
https://dev.classmethod.jp/articles/flutter-keyboard-actions/

これでカスタムキーボードを移植させてみようかなと思った
ちょっと時間ください

**Comment by TakeKiyo** [comment]
承知です！！
