### ISSUE TITLE
行数が少ないときに表示がおかしくなる？

### ISSUE THREAD

**Issue by TakeKiyo** [TakeKiyo/Flutter-CodeScrolling#111]
<img width="394" alt="スクリーンショット 2021-08-29 15 21 56" src="https://user-images.githubusercontent.com/32502331/131240794-a39caa44-6f2f-4254-9e20-3da42e9e6d00.png">

**Comment by matsumo-and** [comment]
StackのPositionedのやつだわ、直します

**Comment by matsumo-and** [comment]
確認しようと思って新しい曲作ろうとしたら

[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
#0      MethodChannelDocumentReference.update (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:59:7)
<asynchronous suspension>

で作れんかった
