### ISSUE TITLE
detailBottomBarをStackで実現する

### ISSUE THREAD

**Issue by matsumo-and** [TakeKiyo/Flutter-CodeScrolling#120]
@TakeKiyo 
歌詞のみページの方にはDetailBottomBar表示しないということでいいよね？

**Comment by TakeKiyo** [comment]
Bpmはあってもいいかなという気持ちはあるけどなー
まあどっちでも良いしリリースして誰かに使ってもらってから判断してもいいかも

**Comment by TakeKiyo** [comment]
いまって歌詞のページで再生はじめたら、コードのページでスクロール始まる？
それとも分離してる？

**Comment by matsumo-and** [comment]
歌詞のページ表示されてる間はコードビューはビルドされてないっぽいから、スクロールもされない！
けど再生してる限りはMetronomeCountStatusは増えてくし、もしかしたら小節分再生したら停止するかも
