### ISSUE TITLE
再生中はAppBarとBottom Barを隠す

### ISSUE THREAD

**Issue by matsumo-and** [TakeKiyo/Flutter-CodeScrolling#121]
AppBar はSliverで実装しなおせばいいのかな

**Comment by TakeKiyo** [comment]
Bottom bar隠すとbpm見えんくならん？

**Comment by TakeKiyo** [comment]
俺の中でこのissueやるよりかは色とかのデザイン整えるほうが優先な気持ちある！

**Comment by matsumo-and** [comment]
>Bottom bar隠すとbpm見えんくならん？

確かに？
Flashさせてる以上表示しとくのが吉か

>俺の中でこのissueやるよりかは色とかのデザイン整えるほうが優先な気持ちある！

オッケー！
