### ISSUE TITLE
全員が見れる曲とかあると良いのかも？

### ISSUE THREAD

**Issue by matsumo-and** [TakeKiyo/Flutter-CodeScrolling#122]
インストールして全部自分で作るっていうのもある程度負担なのかもしれない

アプリの用途によるか

**Comment by TakeKiyo** [comment]
サンプルとして最初に1曲最初から追加されててもいいかなって気はするね
なにをすればいいかわからんってなるの防ぎたいし

**Comment by TakeKiyo** [comment]
ただこれ難しい
ログイン機能をつけてればユーザが作成されたら自動でその人の曲を作成すればいいけど、いまだとそれができない

ホームページとかに詳しい利用方法とか書いとくのがとりあえず楽ではある

**Comment by matsumo-and** [comment]
> ただこれ難しい
ログイン機能をつけてればユーザが作成されたら自動でその人の曲を作成すればいいけど、いまだとそれができない

なるほどなあ

**Comment by TakeKiyo** [comment]
これやる
