### ISSUE TITLE
warningでてる

### ISSUE THREAD

**Issue by TakeKiyo** [TakeKiyo/Flutter-CodeScrolling#138]
![スクリーンショット 2021-09-06 10 30 28](https://user-images.githubusercontent.com/32502331/132148386-0d880a00-cd91-4a24-9dfb-5105aa42b104.png)

これwarning出てるの気になるから、直して欲しい！

**Comment by matsumo-and** [comment]
getter設定してるし、おれのとこは全然出てないんですが！
ダークモードには変えられる？

**Comment by TakeKiyo** [comment]
ごめん今見たら出てなかった

**Comment by TakeKiyo** [comment]
![スクリーンショット 2021-09-06 23 25 38](https://user-images.githubusercontent.com/32502331/132231700-8beece74-2902-4d2e-9bbf-a574a4ab4a5f.png)

代わりにこれ出てる

**Comment by matsumo-and** [comment]
出てないんよなあ
Flutterのバージョン違う？

**Comment by TakeKiyo** [comment]
わからんな
でもとりあえず出てないなら俺の方の問題かもしれんから大丈夫や
