### ISSUE TITLE
画面遷移をルート決めて管理する

### ISSUE THREAD

**Issue by matsumo-and** [TakeKiyo/Flutter-CodeScrolling#16]
多分いちいちDetailPage()とかを指定するより、Main.dartで最初に名前とルート決めといてNavigator.push.Named(/secondpage)とかした方が良いのかも

**Comment by TakeKiyo** [comment]
これ最初にやるべきやな

**Comment by TakeKiyo** [comment]
irealとか使ってて，どんな画面遷移がいいかだいたい決めてくれると嬉しい
osdくん全然やってくれないから

**Comment by matsumo-and** [comment]
なんとなくNotionに書いてみたのはある！もっと詳しく決めないとではある

**Comment by TakeKiyo** [comment]
見ました！
ログインしてない状態ではなにができることを想定してる？

**Comment by matsumo-and** [comment]
ログインしてなくても曲の再生とかリストの閲覧はできるってイメージだったけど違う方が良いかしら！

**Comment by TakeKiyo** [comment]
ログインしてないと曲が存在しなくない？

**Comment by matsumo-and** [comment]
なるほど？
きよしの「曲の情報みれる」っていうのはどういうこと？

**Comment by TakeKiyo** [comment]
Bpmの情報とか歌詞の情報
たぶんDBをローカルに置くか外部に置くかで認識が違ってそう

**Comment by matsumo-and** [comment]
割と理解しました
なるほど！じゃあ基本サインインしてもらうって感じか

**Comment by TakeKiyo** [comment]
ログインしないほうがユーザてきには楽ではある！
今後，bpmとか歌詞の曲情報を共有する機能つけたりするならサインインする前提のほうがとりあえず実装を進める上ではやりやすそう

**Comment by TakeKiyo** [comment]
ローカルのdbを使う方法をあんまり知らないってのもある

**Comment by matsumo-and** [comment]
現状、コード進行とか歌詞もFirebaseで管理とかになる？

**Comment by TakeKiyo** [comment]
サインインする前提ならそう！

**Comment by TakeKiyo** [comment]
別に特にコード書いているわけではないから、いまから決めるっていう段階

**Comment by matsumo-and** [comment]
ちゃんと集まって決めないかん気してきたな、

**Comment by TakeKiyo** [comment]
それはそう

**Comment by matsumo-and** [comment]
画面遷移についてNotionまた書きました @TakeKiyo

**Comment by TakeKiyo** [comment]
曲作成したら、曲の詳細画面行く方が自然な気もするけどどう？

遷移的には一回route戻った方が良さそうな気もするけど

**Comment by matsumo-and** [comment]
確かに！それでもよいな
曲情報入力→コード編集→DetailPageとか？

とりあえずRouteが曲一覧で、Routeに戻るときにはPush使わない的なところさえ統一すればなんでもいけそう

**Comment by TakeKiyo** [comment]
notionに書いてくれたやつで画面遷移はおっけい
