### ISSUE TITLE
曲追加時の入力規則あったら嬉しい

### ISSUE THREAD

**Issue by matsumo-and** [TakeKiyo/Flutter-CodeScrolling#25]
・現実的なbpmの範囲として30~300って一応してるんだけど（全然変わってもいい）、その範囲外になったらダイアログとかで警告出たりするといいかもしれない。PCだからかもしれないけど文字列入れようとするとflutterの方でエラーになるのもある

・タイトルも””だけで登録できちゃうな

**Comment by TakeKiyo** [comment]
https://coflutter.com/flutter-how-to-show-dialog/

**Comment by matsumo-and** [comment]
これに関しては全然showDialog()じゃなくても、範囲外になったらテキストボックスの下に「bpmは〜〜で入力してください」って表示するだけでもいい気がしてきた

**Comment by TakeKiyo** [comment]
どっちみち曲を追加する時に、確認ダイアログ出したほうが操作ミス減るから、成功と失敗の2パターンでほぼ共通してダイアログ出しても良いかなと思ってる

**Comment by matsumo-and** [comment]
なるほど！
ちなみにshowDialog()はdetail_bottom_bar.dart l64でも使っています

**Comment by TakeKiyo** [comment]
初Siri
