### ISSUE TITLE
main menuからSogns listの遷移時にLoagingを表示する

### ISSUE THREAD

**Issue by matsumo-and** [TakeKiyo/Flutter-CodeScrolling#31]
main menuからSongs listに遷移する時、一瞬「エラーが発生しました」って出るから、簡単にasync awaitで非同期処理みたいなことしたほうがいいのかもしれない、よくわからないけど
そのときにLoading画面（ダイアログまたは新しい画面）表示できたらいい感じなのかもしれないと思いました

**Comment by TakeKiyo** [comment]
main menuを廃止　-> ローディング画面

将来的にはロゴとかを入れるところかな

**Comment by TakeKiyo** [comment]
https://enjoy-a-lot.com/flutter-futurebuilder/

**Comment by TakeKiyo** [comment]
https://qiita.com/pikanji/items/7803eaeeb6416a5bcaef

これや
