### ISSUE TITLE
キーボードが出てきて、コードが見えなくなるバグ

### ISSUE THREAD

**Issue by TakeKiyo** [TakeKiyo/Flutter-CodeScrolling#60]
<img width="392" alt="スクリーンショット 2021-08-09 21 22 32" src="https://user-images.githubusercontent.com/32502331/128705405-6eb17922-77c4-4594-8a6b-200f9474e73e.png">

**Comment by TakeKiyo** [comment]
キーボードがフォーカスしてるとこの高さを監視しておいて、それがキーボードの高さを下回っていたら上に引き上げるみたいな感じかなあ

**Comment by TakeKiyo** [comment]
https://yaba-blog.com/flutter-keyboard-form-hidden/
これやろ

**Comment by TakeKiyo** [comment]
カスタムキーボードは難しかった

**Comment by TakeKiyo** [comment]
これって把握してるバグ？
safearea問題みたいなところで本来は解決済み？
https://github.com/TakeKiyo/Flutter-CodeScrolling/pull/55#discussion_r684703887

**Comment by TakeKiyo** [comment]
keyboardIsOpeningがtrueなら、
```
Container(color: Colors.white, width: double.infinity, height:　キーボードの高さ)
```
これを表示とかで対処はできそう

**Comment by matsumo-and** [comment]
それな！！！！
把握してるバグです、今日気づいた

**Comment by matsumo-and** [comment]
> https://yaba-blog.com/flutter-keyboard-form-hidden/
> これやろ

この感じで解決できそう、明日やります
