### ISSUE TITLE
スクロールのスピードをどうやって決めるか

### ISSUE THREAD

**Issue by TakeKiyo** [TakeKiyo/Flutter-CodeScrolling#67]
スクロールのスピードをBPMを基準にして考えてたけど、少し微妙かもしれない

- 4拍を基準に考える分にはいいけど、それ以外のときにずれてしまう
- 歌詞も表示したりすると、歌詞の文字数によって画面に表示される小節数が大きく変わる

から、BPMを基準にスクロールスピードの初期値を与えつつ、BPMとは別にスクロールスピードを変えることのできるスライダー みたいなやつがあった方がいいのかも、と思った

**Comment by matsumo-and** [comment]
何拍子の曲なのかって情報は入力してもらおうかとも個人的には思ってた！

bpm=120の4／4拍子でいえば小節数x4/(bpm/60)が曲の演奏にかかる時間(=seconds)として、その時間でスクロール可能な高さをちょうどスクロールし終えることみたいなのできないのかな
でもあれか、歌詞がめちゃ多い部分と少ない部分と偏ってたらちゃんと表示されないのか

ちょっと調べてみるか

また別途でスライダー表示するとなると、それはそれで演奏とのズレがかなりできそう

**Comment by TakeKiyo** [comment]
あとまあ変拍子とかもあるから、ずっと一定は難しいのかなって思ってる

**Comment by TakeKiyo** [comment]
6段階くらいのスピードから選択する、くらいが無難かもしれん

**Comment by matsumo-and** [comment]
スピードに段階あるって、行きすぎちゃったから遅くしようみたいなことが起こりうるってこと？

それならなんかいっそのことスクロールせずにページシステム的にして最後まで行ったら次のページ、みたいなほうが良いUXそう

連続的なスクロールじゃなくても、行の拍数を取得→その時間過ぎたら次の行をセンターにするみたいなこともできないかな

**Comment by TakeKiyo** [comment]
なるほどなあそれもありやな

**Comment by matsumo-and** [comment]
listidxみたいな変数でテキストフォームの行数は既に持ってるから、たとえば12行あったらスクロール位置を画面全体の1/12とかにする、ってことはできると思う

https://kwmt27.net/2018/09/03/flutter-scroll/

これをおれ試してみてもいいかもしれない
というか、テキストフォームといえこれといえ、コントローラーとかいう神なに？

**Comment by matsumo-and** [comment]
https://github.com/TakeKiyo/Flutter-CodeScrolling/issues/75#issue-970910596
