### ISSUE TITLE
歌詞を実装する

### ISSUE THREAD

**Issue by TakeKiyo** [TakeKiyo/Flutter-CodeScrolling#68]
optionalで、歌詞を追加できるようにする

逆に、歌詞だけを表示してコードは表示しないようにもしたい

https://www.ufret.jp/song.php?data=81523
これのギターコード表示しないバージョンみたいな

**Comment by matsumo-and** [comment]
何拍子とか何小節っていうテンポ情報は持ってる、スクロラーブルな画面での歌詞を単体でってこと？
それとも、ただのテキスト羅列的な画面？

**Comment by TakeKiyo** [comment]
前者！
コードはすでに把握してるから、歌詞だけを共有したいってときもあるかなって感じ

**Comment by TakeKiyo** [comment]
歌詞だけ+スクローラブルな画面は、
自分で作った曲の弾き語りのときに便利かなというイメージ

**Comment by matsumo-and** [comment]
なるほど！
イメージこんな感じ？もっとUfret寄り？
![image](https://user-images.githubusercontent.com/81696417/129463649-7b599b1c-3331-4e5c-95c7-31461c946a80.png)

ufretちょっと歌詞見にくい感あるから、いい歌詞の表示の仕方模索せないかんかもしれんですね

**Comment by TakeKiyo** [comment]
イメージはこんな感じ！

Detailページで、
歌詞だけ表示
コードと歌詞(もしくはコードだけ)
の2パターンを完全に別に実装してもいいかもしれん
とりあえず歌詞は後回しでよさそうだけど

**Comment by matsumo-and** [comment]
り！

bottomPersistetnTabBarみたいなので分けた別々の画面作った方が良さそうでやんすね

**Comment by TakeKiyo** [comment]
それいいね

曲ごとにLyriceOnlyとかCodeAndLyriceみたいなフラグをつけといて、そのフラグによってDetailPageの中で出し分けるとかでもいいんかなと勝手に思ってたけどそっちで良さそう

**Comment by matsumo-and** [comment]
それめちゃむずそうだ
なんかおれも、なんとなく歌詞だけ確認したい用のページあった方がいいなとも思ってたわ！

ちょっとbottomBarとPersistentTabBarの兼ね合いどうしようかって感じだけど

頑張って多段ボトムタブ実装するか
これやるにはbottomBarを画面遷移してもそこに維持するようにNavigator独自に設定しなきゃいけないみたいなのがあるけど、まあなんとかなるでしょう
![image](https://user-images.githubusercontent.com/81696417/129465948-6e5902a2-f369-4c20-83ec-ce1257e2dbb6.png)
