### ISSUE TITLE
ここからここまでA,ここからサビ、みたいな区切りをつけれるようにしたい

### ISSUE THREAD

**Issue by TakeKiyo** [TakeKiyo/Flutter-CodeScrolling#69]
いまのところ、
A
  C | C | D | C
  C | C | D | C
B
  F | F | F | F
  F | F | F | F
サビ
　 F | F | F | F

こんな感じのデザイン？がいいかなと思ってるけどどうですか
@matsumo-and @osd-02

**Comment by matsumo-and** [comment]
いいとおも！
カスタムキーボードの裏面(タブ切り替えみたいな)
で4/4とか🅰️とか入れれるようにしよかなととおもてます

**Comment by matsumo-and** [comment]
キーボードからも1小節とか追加できるようにしよかな

**Comment by TakeKiyo** [comment]
<img width="352" alt="スクリーンショット 2021-08-12 20 16 01" src="https://user-images.githubusercontent.com/32502331/129187947-6aa3fd0f-53f8-421d-92b7-207d5f53296f.png">

スクロールスピードの話とかを考えると、Aとかで1行使うのよくなさそうだから、とりあえずこんな感じでいこうかな

**Comment by matsumo-and** [comment]
![image](https://user-images.githubusercontent.com/81696417/129189039-a818a516-4aea-4ec3-8d45-536473124fed.png)

最終的に上付き文字みたいな感じでやれたらベストな気がする、
