### ISSUE TITLE
拍子を途中で指定する

### ISSUE THREAD

**Issue by matsumo-and** [TakeKiyo/Flutter-CodeScrolling#71]
カスタムキーボードに4/4とか6/8とかキーを作っておいて、それがテキストフォームの先頭にあれば拍子をそれにして、以後指定がなければそれを継続とかしてもいいかも

**Comment by matsumo-and** [comment]
これを監視するモデル新たにつくって、それをスクロール位置に提供するとか天才的

**Comment by TakeKiyo** [comment]
Picker思ったより簡単に実装できるから、
Pickerでも良さそう！

https://qiita.com/tewi_r/items/703676a6eca7bd085180

**Comment by TakeKiyo** [comment]
これ、いったんサビとか4小節と同じ感じで小節を追加するときに横で選択できるようにする感じでもいい？

**Comment by matsumo-and** [comment]
全然大丈夫！！

**Comment by TakeKiyo** [comment]
しゃーやります
