### ISSUE TITLE
現在の再生箇所を色付けまたは進行バーを表示した方がよい？

### ISSUE THREAD

**Issue by matsumo-and** [TakeKiyo/Flutter-CodeScrolling#75]
前のIssueとの関連で、4/4とか拍子を指定するとしたら現在演奏中の箇所とかわかるようにした方がいいかなというところがある。もしそうなら、現在の再生箇所が中央とか見やすいところに配置した方が良いかなとも思った

この辺の再生画面の実装に関してはiRealっぽい画面とUfretっぽい画面、とかで全然求められること違うような気もするのでちゃんと方向性を決めた方がいい気もする

**Comment by TakeKiyo** [comment]
現在の再生場所を色付けするの、技術的に可能ならそれが一番いいと思ってた

**Comment by matsumo-and** [comment]
やるかやらんかよりまず出来るかだったわ、ちょいむずそうなので考えてみます
Key指定でなんとかならんかという考え
