### ISSUE TITLE
アーティスト情報などなど欲しい

### ISSUE THREAD

**Issue by matsumo-and** [TakeKiyo/Flutter-CodeScrolling#78]
アーティスト名
曲名
BPM
キー（Cメジャーとか）　←指定したらカポ設定とか変調とか対応できるかもしれん

みたいな作成画面でもいいかもしれません！！

**Comment by TakeKiyo** [comment]
これやったら、#76やろう

**Comment by TakeKiyo** [comment]
いったんこれやるわ
