### ISSUE TITLE
実機ならではのバグ発見しました

### ISSUE THREAD

**Issue by matsumo-and** [TakeKiyo/Flutter-CodeScrolling#87]
<img width="414" alt="スクリーンショット 2021-08-18 21 58 34" src="https://user-images.githubusercontent.com/81696417/129905450-f90f90f2-7da3-4fa5-8971-6198381bee92.png">

解決方法ちょっと僕にはよくわかりません、一旦共有

**Comment by TakeKiyo** [comment]
悲しい
僕がやります

**Comment by TakeKiyo** [comment]
これってなにしたときに発生したかわかる？手元で再現できん

**Comment by matsumo-and** [comment]
曲名とかアーティスト入力するときに、キーボードが出てくるとこうなる！

**Comment by TakeKiyo** [comment]
確認できた！やります
