### ISSUE TITLE
編集を終了したときに、DetailPageに戻るときと戻らないときがある

### ISSUE THREAD

**Issue by TakeKiyo** [TakeKiyo/Flutter-CodeScrolling#92]
キーボードが閉じるだけのときと、DetailPageに戻るときがある

編集を終了ボタンを押したらダイアログを出せば解決する気もする

**Comment by TakeKiyo** [comment]
そんなに重要じゃないこれ

**Comment by matsumo-and** [comment]
これも、キーボードが実際Bottom Sheetだから、Pop UntilとかでDetailPageに戻れば解決します

**Comment by TakeKiyo** [comment]
これやります
